/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/minimalistic_modern_office.glb --transform --shadows --instance
Author: dylanheyes (https://sketchfab.com/dylanheyes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minimalistic-modern-office-5540183da1c7452f810f8de33734879a
Title: Minimalistic Modern Office
*/

import React, { useEffect, useLayoutEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { DoubleSide, Vector3 } from "three";
import { gsap } from "gsap";

export function Room({ tl, ...otherProps }) {
	const { nodes, materials } = useGLTF(
		"/models/minimalistic_modern_office-transformed.glb",
	);
	const group = useRef();
	const chair = useRef();
	const model = useRef();

	useEffect(() => {
		Object.values(materials).forEach((material) => {
			material.side = DoubleSide;
			material.envMapIntensity = 0;

			gsap.to(material, {
				envMapIntensity: 1,
				duration: 2.25,
				delay: 1.25,
				ease: "power2.out",
			});
		});
	}, []);

	useLayoutEffect(() => {
		if (tl) {
			tl.to(
				model.current.scale,
				{
					x: 0,
					y: 0,
					z: 0,
					duration: 0.25,
				},
				1.5,
			);
		}
	}, [tl]);

	return (
		<group {...otherProps} ref={model} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]} scale={0.35}>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<group
						ref={group}
						rotation={[-Math.PI / 2, Math.PI / 2, 0]}
						scale={[410, 1230, 410]}
					>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Glass_0
									.geometry
							}
							material={materials.Glass}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Structure_0
									.geometry
							}
							material={materials.Structure}
						/>
						{/* <mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Background_0
									.geometry
							}
							material={materials.Background}
						/> */}
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Table_0
									.geometry
							}
							material={materials.Table}
						/>
						<mesh
							ref={chair}
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Chair_0
									.geometry
							}
							material={materials.Chair}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Plants_0
									.geometry
							}
							material={materials.Plants}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Plants_0_1
									.geometry
							}
							material={materials.Plants}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Lights_0
									.geometry
							}
							material={materials.Lights}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_LightEmission_0
									.geometry
							}
							material={materials.LightEmission}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.Carpet_Carpet_0.geometry}
							material={materials.Carpet}
							position={[1, 0, 2.44]}
							rotation={[0, -Math.PI / 2, 0]}
							scale={[1.39, 0.46, 1.39]}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

export function WireRoom({ wireframe, ...otherProps }) {
	const { nodes, materials } = useGLTF(
		"/models/minimalistic_modern_office-transformed.glb",
	);

	useEffect(() => {
		Object.values(materials).forEach((material) => {
			material.side = DoubleSide;
			material.wireframe = true;
		});
	}, []);

	return (
		<group {...otherProps} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]} scale={0.35}>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<group
						rotation={[-Math.PI / 2, Math.PI / 2, 0]}
						scale={[410, 1230, 410]}
					>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Glass_0
									.geometry
							}
							material={materials.Glass}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Structure_0
									.geometry
							}
							material={materials.Structure}
						/>
						{/* <mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Background_0
									.geometry
							}
							material={materials.Background}
						/> */}
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Table_0
									.geometry
							}
							material={materials.Table}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Chair_0
									.geometry
							}
							material={materials.Chair}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Plants_0
									.geometry
							}
							material={materials.Plants}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Plants_0_1
									.geometry
							}
							material={materials.Plants}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Lights_0
									.geometry
							}
							material={materials.Lights}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_LightEmission_0
									.geometry
							}
							material={materials.LightEmission}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.Carpet_Carpet_0.geometry}
							material={materials.Carpet}
							position={[1, 0, 2.44]}
							rotation={[0, -Math.PI / 2, 0]}
							scale={[1.39, 0.46, 1.39]}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/models/minimalistic_modern_office-transformed.glb");
